import Head from 'next/head';

import styles from '../styles/common.module.css';

import { MainLayout } from '../app/components/MainLayout';

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Main page</h1>
      </main>
    </MainLayout>
  );
}
